### ISSUE TITLE
Out of date releases

### ISSUE THREAD

**Issue by SJrX** [JetBrains/Grammar-Kit#290]
I have been having issues getting my project to work with 2021.3 EAP (last builds were against 2021.1) and of course I tried updating to the latest version 2021.1.2 (https://github.com/JetBrains/Grammar-Kit/releases), except that the latest release is 2021.1.3 (https://plugins.gradle.org/plugin/org.jetbrains.grammarkit). I only figured out that was the problem because I tried to go back to 2021.2 and got the error described in #283 which gave me a confused look as there was no 2021.1.3

For the purposes of a google searching I'll include the stack trace I was trying to figure out so people can find it:

```
Exception in thread "main" java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/objects/ObjectOpenCustomHashSet
	at com.intellij.core.CoreFileTypeRegistry.<init>(CoreFileTypeRegistry.java:21)
	at com.intellij.core.CoreApplicationEnvironment.<init>(CoreApplicationEnvironment.java:86)
	at com.intellij.core.CoreApplicationEnvironment.<init>(CoreApplicationEnvironment.java:77)
	at org.intellij.grammar.LightPsi$MyParsing.<init>(LightPsi.java:155)
	at org.intellij.grammar.LightPsi.<clinit>(LightPsi.java:54)
	at org.intellij.grammar.Main.main(Main.java:37)
Caused by: java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.objects.ObjectOpenCustomHashSet
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
Caused by: java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.objects.ObjectOpenCustomHashSet

	... 6 more
```

**Comment by Anadyrskie** [comment]
For posterity, change the version in "plugins" not in "grammarKit" settings.
`plugins {
    id "org.jetbrains.grammarkit" version "2021.1.3"
}

grammarKit {
    grammarKitRelease = "2021.1.2"
}`

**Comment by SJrX** [comment]
Lol just noticed the releases aren't out of date, this repository is for the IntelliJ Plugin, the Gradle plugin is here: https://github.com/JetBrains/gradle-grammar-kit-plugin
